user:
  # 姓名,id
  - name: '王天航'
    # 晨检
    morningCheck:
      enable: true # 是否开启,true/false,如果为空[checkTime]和[endTime]可以为空
      checkTime: '11:20:00' # 执行签到的时间
      endTime: '12:00:00' # 签到时间,签到的机制是,在大于[checkTime]并小于[endTime]之间执行,一天只会执行一次
    # 午检
    afternoonCheck:
      enable: true
      checkTime: '17:20:00'
      endTime: '18:00:00'
    # 晚检签到(可直接用于签到)
    eveningCheck:
      enable: false
      checkTime: '23:50:00'
      endTime: '23:59:00'
    # 健康打卡(西石大研究生使用)
    healthCheck:
      enable: false
      checkTime: '12:00:00'
      endTime: '23:59:00'
    # 我在校园密钥
    jwsession: 'f46a2d76b23a449c841245fc9c245ec8'
    # qq机器人,用做反馈和接收代签情况
    # powered by: https://github.com/solywsh/qqBot-revue
    # 在使用前需要添加qq 3056159050为好友,发送`/help`根据提示获取密钥
    # 如果enable为false,[userId]和[token]可以为空
    # 也可以根据链接自己部署一个revue机器人,如果你有好的建议,欢迎到仓库提交issue
    qqBotRevue:
      enable: true # 是否开启true/false
      module: brief # 消息发送方式brief/detailed,brief只发送人数,detailed发送名单
      qq:
        - userId: '1228014966' # 接收消息的qq1
          token: '35406ce1-7dd2-41ca-9e46-d786deaca5f8' # 获取到的token,注意qq和token为绑定关系
#        - userId: '' # 接收消息的qq2
#          token: '' # 获取到的token,注意qq和token为绑定关系
    # 设备标识,用以规避更换设备登录提示,这里建议使用自己手机的设备标识
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.18(0x18001236) NetType/WIFI Language/zh_CN'
    # 所在省份,在日检日报提交表单哈希时使用
    province: '陕西省'
    # 所在省份的城市,在日检日报提交表单哈希时使用
    city: '西安市'